language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo sed -i 's/#START=yes/START=yes/' /etc/default/beanstalkd
  - sudo service beanstalkd start
  - cat /etc/init.d/beanstalkd | sed 's/NAME=beanstalkd/NAME=beanstalkd2/' | sudo tee /etc/init.d/beanstalkd2 2>&1>/dev/null
  - cat /etc/default/beanstalkd | sed 's/11300/11301/' | sudo tee /etc/default/beanstalkd2 2>&1>/dev/null
  - sudo chmod +x /etc/init.d/beanstalkd2
  - sudo service beanstalkd2 start

env:
  - BEANSTALK_ADDRESSES='beanstalk://localhost:11300,beanstalk://localhost:11301'

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
